apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service-api
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expense-service-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - expense-service-api
              topologyKey: nodes
      containers:
        - image: "prashantdocker87/eks-demo:2567e5a"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: service-port
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: expense-service-api
          ports:
            - containerPort: 8080
              name: service-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: service-port
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
            requests:
              cpu: 200m
              memory: 400Mi
      restartPolicy: Always
